spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl-auto: validate

  application:
    name: projectone
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
